In [1]:
import numpy as np

In [2]:
# Problem: Add two arrays a and b element-wise.
# Input:
# a = np.array([10, 20, 30, 40])
# b = np.array([1, 2, 3, 4])
# Expected Output: [11 22 33 44]

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
a+b

array([11, 22, 33, 44])

In [3]:
# Problem: Multiply two arrays a and b element-wise.
# Input:
# a = np.array([2, 4, 6])
# b = np.array([3, 5, 7])
# Expected Output: [ 6 20 42]

a = np.array([2, 4, 6])
b = np.array([3, 5, 7])
a*b

array([ 6, 20, 42])

In [4]:
# Problem: Compute the square of each element in array a.
# Input: a = np.array([1, 2, 3, 4, 5])
# Expected Output: [ 1 4 9 16 25]

a = np.array([1, 2, 3, 4, 5])
a**2

array([ 1,  4,  9, 16, 25])

In [7]:
# Problem: Compute the square root of each element in array a.
# Input: a = np.array([1, 4, 9, 16, 25])
# Expected Output: [1. 2. 3. 4. 5.]

a = np.array([1, 4, 9, 16, 25])
# a**0.5  or
np.sqrt(a)

array([1., 2., 3., 4., 5.])

In [8]:
# Problem: Compute the natural logarithm (base $e$) of array a
# Input: a = np.array([1, np.e, np.e**2])
# Expected Output: [0. 1. 2.]

a = np.array([1, np.e, np.e**2])
np.log(a)

array([0., 1., 2.])

In [11]:
# Problem: Calculate the dot product of two 1D vectors.
# a = np.array([1, 2, 3])
# b = np.array([4, 5, 6])
# Expected Output: 32  (Calculation: 1*4 + 2*5 + 3*6)


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a,b)

np.int64(32)

In [12]:
# Problem: Perform matrix multiplication (dot product) on two 2D matrices.
# Inputs:
# a = np.array([[1, 2], [3, 4]])
# b = np.array([[5, 6], [7, 8]])
# Expected Output:
# [[19 22]
#  [43 50]]

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [13]:
# Problem: Find the sum of all elements in the array.
# Input: a = np.array([[1, 2], [3, 4]])
# Expected Output: 10

a = np.array([[1, 2], [3, 4]])
np.sum(a)

np.int64(10)

In [14]:
# Problem: Calculate the sum of each column.
# Inputs:
# a = np.array([[1, 2, 3],
#               [4, 5, 6]])
# Expected Output: [5 7 9]

a = np.array([[1, 2, 3],[4, 5, 6]])
np.sum(a,axis=0)

array([5, 7, 9])

In [18]:
# Problem: Calculate the average value of each row .
# Input:
# a = np.array([[10, 20, 30],
#               [40, 50, 60]])
# Expected Output: [20. 50.]

a = np.array([[10, 20, 30],[40, 50, 60]])
np.mean(a,axis=1)

array([20., 50.])

In [21]:
# Problem: Find the smallest value in the entire array.
# Input: a = np.array([10, 5, 8, 3, 9])
# Expected Output: 3

a = np.array([10, 5, 8, 3, 9])
int(np.min(a))

3

In [27]:
# Problem: Find the index (position) of the maximum value in the array.
# Input: a = np.array([10, 50, 30, 20])
# Expected Output: 1 (Since 50 is at index 1)

a = np.array([10, 50, 30, 20])
int(np.argmax(a))

1

In [28]:
# Problem: Find the index of the maximum value in each row.
# Input:
# a = np.array([[1, 2, 3],
#               [6, 5, 4]])
# Expected Output: [2 0] (3 is max in row 0 at idx 2; 6 is max in row 1 at idx 0)

a = np.array([[1, 2, 3],[6, 5, 4]])
np.argmax(a,axis=1)

array([2, 0])

In [29]:
# Problem: Compute the cumulative sum of the elements.
# Input: a = np.array([1, 2, 3, 4, 5])
# Expected Output: [ 1 3 6 10 15]

a = np.array([1, 2, 3, 4, 5])
np.cumsum(a)

array([ 1,  3,  6, 10, 15])

In [30]:
# Problem: Calculate the difference between the maximum and minimum values (ptp).
# Input: a = np.array([1, 5, 10, 20])
# Expected Output: 19

a = np.array([1, 5, 10, 20])
int(np.max(a))-int(np.min(a))

19

In [32]:
# Problem: Add a 1D array b to each row of a 2D array a.
# Input:
# a = np.array([[1, 1, 1],[1, 1, 1]])
# b = np.array([0, 1, 2])
# Expected Output:[[1 2 3],[1 2 3]]

a = np.array([[1, 1, 1],[1, 1, 1]])
b = np.array([0, 1, 2])
np.add(a,b)

array([[1, 2, 3],
       [1, 2, 3]])

In [33]:
# Problem: Multiply a 2D array a by a column vector b.
# Input:
# a = np.array([[1, 2, 3],
#               [4, 5, 6]])
# b = np.array([[10],
#               [20]])
# Expected Output:[[ 10  20  30], [ 80 100 120]]

a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[10],[20]])
a*b

array([[ 10,  20,  30],
       [ 80, 100, 120]])

In [34]:
# Problem: Limit the values in the array so that values less than 10 become 10, and values greater than 20 become 20.
# Input: a = np.array([5, 10, 15, 20, 25])
# Expected Output: [10 10 15 20 20]

a = np.array([5, 10, 15, 20, 25])
np.clip(a,10,20)

array([10, 10, 15, 20, 20])

In [41]:
# Problem: Calculate the Euclidean distance between two points (vectors) a and b.(Hint: $\sqrt{\sum(a_i - b_i)^2}$)
# Input:a = np.array([1, 2])
# b = np.array([4, 6])
# Expected Output: 5.0

a = np.array([1, 2])
b = np.array([4, 6])
# np.sqrt(np.sum((a-b)**2))  or
np.linalg.norm(a - b)

np.float64(5.0)

In [45]:
# Problem: Normalize array a by subtracting the mean and dividing by the standard deviation.
# Input: a = np.array([10, 20, 30, 40, 50])
# Expected Output: [-1.414 -0.707 0. 0.707 1.414] (approx)

a = np.array([10, 20, 30, 40, 50])
np.round((a-np.mean(a))/np.std(a),3)

array([-1.414, -0.707,  0.   ,  0.707,  1.414])