In [2]:
import numpy as np

In [3]:
# Problem: Extract all values greater than 5 from the array.
# Input: arr = np.array([1, 8, 3, 9, 2, 6])
# Expected Output: [8 9 6]

arr = np.array([1, 8, 3, 9, 2, 6])
arr[arr>5]

array([8, 9, 6])

In [4]:
# Problem: Extract all even numbers from the array.
# Input: arr = np.array([10, 15, 20, 25, 30])
# Expected Output: [10 20 30]

arr = np.array([10, 15, 20, 25, 30])
arr[arr%2==0]

array([10, 20, 30])

In [5]:
# Problem: Select elements from arr where mask is True.
# Input:  arr = np.array([1, 2, 3, 4])
#         mask = np.array([True, False, True, False])
# Expected Output: [1 3]

arr = np.array([1, 2, 3, 4])
mask = np.array([True, False, True, False])
arr[mask]

array([1, 3])

In [6]:
# Problem: Extract all elements that are NOT greater than 5 (do not use < or <=, use the ~ operator).
# Input: arr = np.array([1, 8, 3, 9, 2, 6])
# Expected Output: [1 3 2]

arr = np.array([1, 8, 3, 9, 2, 6])
mask = arr > 5
arr[~mask]

array([1, 3, 2])

In [7]:
# Problem: Replace all values less than 0 with 0 in the original array.
# Input: arr = np.array([-1, 2, -3, 4, -5])
# Expected Output: [0 2 0 4 0]

arr = np.array([-1,2,-3,4,-5])
np.where(arr<0,0,arr)

array([0, 2, 0, 4, 0])

In [8]:
# Problem: Create a new array where values > 5 are kept as is, but values <= 5 are replaced with -1.
# Input: arr = np.array([1, 8, 3, 9, 2, 6])
# Expected Output: [-1 8 -1 9 -1 6]

arr = np.array([1, 8, 3, 9, 2, 6])
np.where(arr>5,arr,-1)

array([-1,  8, -1,  9, -1,  6])

In [9]:
# Problem: Find the indices (positions) of all elements that are greater than 10.
# Input: arr = np.array([5, 15, 8, 20, 3])
# Expected Output: (array([1, 3]),)

arr = np.array([5, 15, 8, 20, 3])
np.where(arr>10)

(array([1, 3]),)

In [10]:
# Problem: Use np.where to convert "True" to 1 and "False" to 0.
# Input: arr = np.array([True, False, True])
# Expected Output: [1 0 1]

arr = np.array([True, False, True])
np.where(arr==True,1,0)

array([1, 0, 1])

In [11]:
# Problem: Extract values that are greater than 5 AND less than 20.
# Input: arr = np.array([1, 8, 3, 9, 25, 6, 30])
# Expected Output: [8 9 6]

arr = np.array([1, 8, 3, 9, 25, 6, 30])
arr[(arr>5) & (arr<20)]

array([8, 9, 6])

In [12]:
# Problem: Extract values that are either less than 3 OR greater than 15.
# Input: arr = np.array([1, 10, 2, 20, 5, 30])
# Expected Output: [ 1 2 20 30]

arr = np.array([1, 10, 2, 20, 5, 30])
arr[(arr<3) | (arr>15)]

array([ 1,  2, 20, 30])

In [13]:
# Problem: Extract all valid numbers (exclude nan) from the array.
# Input: arr = np.array([1, np.nan, 3, np.nan, 5])
# Expected Output: [1. 3. 5.] (Hint: Use np.isnan)

arr = np.array([1, np.nan, 3, np.nan, 5])
arr[~np.isnan(arr)]

array([1., 3., 5.])

In [14]:
# Problem: Check if any value in the array is greater than 100. Returns a single boolean.
# Input: arr = np.array([1, 50, 99, 10])
# Expected Output: False

arr = np.array([1, 50, 99, 10])
bool(np.any(arr>100))

False

In [15]:
# Problem: Sort the array in ascending order.
# Input: arr = np.array([3, 1, 2])
# Expected Output: [1 2 3]

arr = np.array([3, 1, 2])
np.sort(arr)

array([1, 2, 3])

In [16]:
# Problem: Sort the array in descending order.
# Input: arr = np.array([3, 1, 2])
# Expected Output: [3 2 1]

arr = np.array([3, 1, 2])
np.sort(arr)[::-1]

array([3, 2, 1])

In [17]:
# Problem: Get the indices that would sort the array.
# Input: arr = np.array([50, 10, 20])
# Expected Output: [1 2 0] (Explanation: 10 is at idx 1, 20 at idx 2, 50 at idx 0)

arr = np.array([50, 10, 20])
np.argsort(arr)

array([1, 2, 0])

In [18]:
# Problem: Sort each row of the matrix independently.
# Input:arr = np.array([[5, 2, 9],[1, 6, 4]])
# Expected Output:[[2 5 9],[1 4 6]]

arr = np.array([[5, 2, 9],[1, 6, 4]])
np.sort(arr,axis=1)

array([[2, 5, 9],
       [1, 4, 6]])

In [19]:
# Problem: Sort each column of the matrix independently.
# Input:  arr = np.array([[5, 2, 9],[1, 6, 4]])
# Expected Output:[[1 2 4],[5 6 9]]

arr = np.array([[5, 2, 9],[1, 6, 4]])
np.sort(arr,axis=0)

array([[1, 2, 4],
       [5, 6, 9]])

In [20]:
# Problem: Sort the entire 2D array based on the values in the second column (index 1).
# Input: arr = np.array([[1, 5, 0],[3, 2, 0],[0, 9, 0]])
# Expected Output:
# [[3 2 0]   <-- 2 is smallest in col 1
#  [1 5 0]   <-- 5 is next
#  [0 9 0]]  <-- 9 is largest

arr = np.array([[1, 5, 0],[3, 2, 0],[0, 9, 0]])
arr[np.argsort(arr[:,1])]

array([[3, 2, 0],
       [1, 5, 0],
       [0, 9, 0]])

In [21]:
# Problem: Find the unique values in the array (remove duplicates).
# Input: arr = np.array([1, 2, 2, 3, 3, 3])
# Expected Output: [1 2 3]

arr = np.array([1, 2, 2, 3, 3, 3])
np.unique(arr)

array([1, 2, 3])

In [22]:
# Problem: Find the unique values and how many times each appears.
# Input: arr = np.array(['a', 'b', 'b', 'c', 'a', 'a'])
# Expected Output:(array(['a', 'b', 'c'], dtype='<U1'), array([3, 2, 1]))

arr = np.array(['a', 'b', 'b', 'c', 'a', 'a'])
np.unique_counts(arr)

UniqueCountsResult(values=array(['a', 'b', 'c'], dtype='<U1'), counts=array([3, 2, 1]))

In [24]:
# Problem: Find the value in the array arr that is closest to a given scalar x. (Hint: Use abs and argmin)
# Input: arr = np.array([10, 25, 40, 55, 70])
# x = 42
# Expected Output: 40

arr = np.array([10, 25, 40, 55, 70])
x = 42
int(arr[np.argmin(np.abs(arr-x))])

40

In [25]:
# Problem: Replace all values that are more than 1 standard deviation away from the mean with the mean value.
# Input: arr = np.array([1, 2, 3, 100, 5, 6])
# Expected Output:[ 1.   2.   3.  19.5  5.   6. ]

arr = np.array([1, 2, 3, 100, 5, 6])
x = np.std(arr)
np.set_printoptions(precision=1)
np.where(arr>x,np.mean(arr),arr)

array([ 1. ,  2. ,  3. , 19.5,  5. ,  6. ])

In [26]:
# Problem: From a 2D array, extract only the rows where the value in the second column is greater than 10.
# Input:arr = np.array([[1, 20, 3],
#                       [4, 5, 6],
#                       [7, 15, 9]])
# Expected Output:[[ 1 20  3]
#                  [ 7 15  9]]

arr = np.array([[1, 20, 3],
                [4, 5, 6],
                [7, 15, 9]])
arr[np.where(arr[:,1]>10)]

array([[ 1, 20,  3],
       [ 7, 15,  9]])

In [27]:
arr = np.array([10, 5, 20, 3, 100, 50])
res = np.partition(arr,-3)
res[-3:]

array([ 20, 100,  50])

In [28]:
arr = np.array([[1, 2, 3],
                [4, np.nan, 6],
                [7, 8, 9]])
x = np.any(np.isnan(arr),axis=1)
arr[~x]

array([[1., 2., 3.],
       [7., 8., 9.]])

In [29]:

indices = np.array([1, 0, 3])   # category indices
one_hot = np.eye(4)[indices]
one_hot

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])