In [2]:
import numpy as np

In [58]:
#create an empty and a full NumPy array
arr1 = np.empty((2,2))
arr2 = np.full((2,2),7)
arr1,arr2

(array([[4.9e-324, 9.9e-324],
        [1.5e-323, 2.0e-323]]),
 array([[7, 7],
        [7, 7]]))

In [30]:
#create an array of zeros
zeros_arr = np.zeros((2,2))
zeros_arr

array([[0., 0.],
       [0., 0.]])

In [31]:
# How to create a boolean array?
arr = np.full((3,3),True,dtype=bool) #M-1
arr = np.ones((3,3),dtype=bool) #M-2
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [32]:
# Question : Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [33]:
# Question: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [34]:
# Question: Replace all odd numbers in arr with -1 without changing arr
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: out
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a = np.arange(10)
b = a.copy()
b[b%2==1] = -1
a,b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]))

In [37]:
# Question: Convert a 1D array to a 2D array with 2 rows
# input: np.arange(10)
# output array([[0, 1, 2, 3, 4],
#               [5, 6, 7, 8, 9]])
a = np.arange(10)
a.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
# Question: Stack arrays a and b vertically
# input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)

# output: array([[0, 1, 2, 3, 4],
#                [5, 6, 7, 8, 9],
#                [1, 1, 1, 1, 1],
#                [1, 1, 1, 1, 1]])

# Solution
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [48]:
# Question: Stack the arrays a and b horizontally.

# Input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)
# Output: array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#                [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [51]:
# Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)


array([2, 4])

In [52]:
# Question: From array a remove all items present in array b

# Input: a = np.array([1,2,3,4,5])
#        b = np.array([5,6,7,8,9])

# Output: array([1,2,3,4])

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [53]:
# Question: Get the positions where elements of a and b match

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: (array([1, 3, 5, 7]),)

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

In [56]:
# Question: Get all items between 5 and 10 from a.

# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])
# Output: (array([6, 9, 10]),)

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

In [3]:
# Q1 Find element-wise maximum of two array
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# Output:
# array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
np.maximum(a,b)   #or  np.where(a>b,a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [4]:
# Question: Swap columns 1 and 2 in the array arr.
#input:
# array([[0, 1, 2],
#       [3, 4, 5],
#       [6, 7, 8]])
# Output:
# array([[1, 0, 2],
#        [4, 3, 5],
#        [7, 6, 8]])

arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [5]:
# Question: Swap rows 1 and 2 in the array arr:
#input:
# array([[0, 1, 2],
#       [3, 4, 5],
#       [6, 7, 8]])
# Output:
# array([[3, 4, 5],
#        [0, 1, 2],
#        [6, 7, 8]])

arr = np.arange(9).reshape(3,3)
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [6]:
# Question: Reverse the rows of a 2D array arr.
#input:
# array([[0, 1, 2],
#       [3, 4, 5],
#       [6, 7, 8]])
# Output:
# array([[6, 7, 8],
#        [3, 4, 5],
#        [0, 1, 2]])

arr = np.arange(9).reshape(3,3)
arr[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [7]:
# Question: Reverse the columns of a 2D array arr.
#Input:
# array([[0, 1, 2],
#       [3, 4, 5],
#       [6, 7, 8]])
# Output:
# array([[2, 1, 0],
#        [5, 4, 3],
#        [8, 7, 6]])

arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [8]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
arr = np.random.uniform(5,10,(5,3))
arr

array([[5.07700342, 9.15706357, 6.3325412 ],
       [9.29034306, 6.80686377, 5.67113367],
       [7.06611919, 6.79383425, 6.47238671],
       [8.90083913, 7.17862511, 7.35794161],
       [6.66767974, 9.90363017, 8.20343915]])

In [9]:
# Question: Print or show only 3 decimal places of the numpy array rand_arr.
# Input: rand_arr = np.random.random((5,3))
# # Output: array([[0.855, 0.543, 0.753],
#        [0.746, 0.189, 0.232],
#        [0.015, 0.383, 0.575],
#        [0.173, 0.552, 0.485],
#        [0.402, 0.483, 0.565]])
arr = np.random.random((5,3))
np.set_printoptions(precision=3)
arr

array([[0.824, 0.481, 0.805],
       [0.625, 0.195, 0.328],
       [0.158, 0.862, 0.018],
       [0.447, 0.175, 0.97 ],
       [0.907, 0.411, 0.992]])

In [10]:
# Question: Limit the number of items printed in python numpy array a to a maximum of 6 elements.a
arr = np.arange(15)
np.set_printoptions(threshold=6)
arr

array([ 0,  1,  2, ..., 12, 13, 14], shape=(15,))